### ISSUE TITLE
Add description to Cargo.toml of each crate

### ISSUE THREAD

**Issue by amanjeev** [hawkw/alarm#49]
Please add `description` field to the `Cargo.toml` with appropriate explanation. This will help understand what different crates do.

In addition to this, do you think there should be an explanation in README.md?

**Comment by hawkw** [comment]
@amanjeev I think the README definitely ought to have a description of the repo contents, good call! IMO this is somewhat more of a priority than adding `description` fields to the `Cargo.toml` files for each crate, since a majority of them will probably not be published to crates.io, but I may as well do that at the same time.

**Comment by hawkw** [comment]
Tada!

**Comment by amanjeev** [comment]
Yay! Thanks!
